services:
  ledge:
    image: ledge:latest
    container_name: ledge
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/video0:/dev/video0
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - .:/app/LEDGE                  # Mount this code in docker container for development
      - /home/mikura-iit.local/data:/data # Mount recorded data from host. Please change directory.
    environment:
      - DISPLAY=unix$DISPLAY
      
    network_mode: host
    command: sleep infinity